Repository cabralcaio/helpr-back-jfs5, pull requests merged in 2022-12, with the labels that each got.

#5 Entidade FuturoCandidato e Repository FuturoCandidato
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Setor.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoReposytory.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#9 Padronização de senha do banco de dados
  src/main/resources/application-dev.properties
Labels: bug

#10 DTO de Futuro Candidato
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoCandidatoDTO.java
Labels: enhancement

#13 Concluido FuturoCandidatoService
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidatoService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#15 Controller de futuro candidato concluido e testado
  src/main/java/org/soulcodeacademy/helpr/config/SecurityConfig.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoCandidatoController.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidatoService.java
Labels: enhancement

#19 DependenteController
  src/main/java/org/soulcodeacademy/helpr/controllers/DependenteController.java
  src/main/java/org/soulcodeacademy/helpr/domain/Dependente.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/DependenteDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/StatusChamado.java
  src/main/java/org/soulcodeacademy/helpr/repositories/DependenteRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/DependenteService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/resources/application.properties
Labels: enhancement

#20 Entidade e Repository Dependente
  src/main/java/org/soulcodeacademy/helpr/domain/Dependente.java
  src/main/java/org/soulcodeacademy/helpr/repositories/DependenteRepository.java
Labels: enhancement

#21 Service e Dto Dependente
  src/main/java/org/soulcodeacademy/helpr/domain/dto/DependenteDTO.java
  src/main/java/org/soulcodeacademy/helpr/services/DependenteService.java
Labels: enhancement

#22 Novo status Arquivado
  src/main/java/org/soulcodeacademy/helpr/domain/enums/StatusChamado.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#25 Serviço de usuário criado com os devidos filtros
  src/main/java/org/soulcodeacademy/helpr/services/UsuarioService.java
Labels: enhancement

#26 Usuário controller criado
  src/main/java/org/soulcodeacademy/helpr/controllers/UsuarioController.java
  src/main/java/org/soulcodeacademy/helpr/repositories/UsuarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/UsuarioService.java
Labels: enhancement

#28 inclui as anotações preAuthorize para proteger endpont de chamados
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
Labels: enhancement

#30 inclui a anotaÃacao preAuthorize no clienteController
  src/main/java/org/soulcodeacademy/helpr/controllers/ClienteController.java
Labels: enhancement

#32 atulização para o funcionamento do deletar futuro candidato
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoCandidatoController.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidatoService.java
Labels: enhancement

#33 inclui anotaacao PreAuthorize no campo FuncionarioController
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
Labels: enhancement

#34 Incluido função que detecta usuario logado
  src/main/java/org/soulcodeacademy/helpr/controllers/UsuarioController.java
  src/main/java/org/soulcodeacademy/helpr/services/UsuarioService.java
Labels: enhancement

#36 gerador de pdf de chamados
  pom.xml
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/utils/PDFGenerator.java
Labels: enhancement

#37 Readme e adição de fotos
  README.md
  src/assets/images/mesdtn.png
  src/assets/images/projetohelpr.png
Labels: documentation
